// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/devmizumizurice/go-jwt/controllers"
	"github.com/devmizumizurice/go-jwt/repositories"
	"github.com/devmizumizurice/go-jwt/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAuthController(db *gorm.DB) controllers.AuthControllerInterface {
	userRepositoryInterface := repositories.NewUserRepository(db)
	authServiceInterface := services.NewAuthService(userRepositoryInterface)
	authControllerInterface := controllers.NewAuthController(authServiceInterface)
	return authControllerInterface
}

func InitializeUserController(db *gorm.DB) controllers.UserControllerInterface {
	userRepositoryInterface := repositories.NewUserRepository(db)
	userServiceInterface := services.NewUserService(userRepositoryInterface)
	userControllerInterface := controllers.NewUserController(userServiceInterface)
	return userControllerInterface
}
